[package]
name = "wasabi"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
cargo-husky = { version = "1.5.0", default-features = false, features = [
  "user-hooks",
] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
